### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IzzySoft** [SummerOak/NetCloud_android#2]
Could you please specify what license your project uses? Placing the license file inside the root of your project, when properly named, would make Github recognize it and show it in the head line (next to "contributor"). Also, with a FLOSS license, your app could be listed at [F-Droid](https://f-droid.org/) (I gladly help you with that if you want).

**Comment by SummerOak** [comment]
> Could you please specify what license your project uses? Placing the license file inside the root of your project, when properly named, would make Github recognize it and show it in the head line (next to "contributor"). Also, with a FLOSS license, your app could be listed at [F-Droid](https://f-droid.org/) (I gladly help you with that if you want).

OK, a GPL license has added to my project. Thanks for your suggestion @IzzySoft .

**Comment by IzzySoft** [comment]
Thanks a lot, @SummerOak! Do you want your app listed in F-Droid? Just let me know and I get it started (well, actually I just added it [to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.summer.netcloud) :wink:).

**Comment by SummerOak** [comment]
@IzzySoft Go ahead,  you can listed it in F-Droid if you want.

**Comment by IzzySoft** [comment]
Thanks! [RFP created](https://gitlab.com/fdroid/rfp/issues/747).

**Comment by IzzySoft** [comment]
@SummerOak one of our devs (who wanted to process the inclusion) found some "prebuilt binaries" in https://github.com/SummerOak/NetCloud_android/tree/master/app/libs – could you please check (and eliminate)? Thanks!

**Comment by SummerOak** [comment]
@IzzySoft  I can't remove that library , but the source code of that library is also open source in my repositories: https://github.com/SummerOak/VpnService_android

**Comment by IzzySoft** [comment]
That helps solving it: could you add it to the build process instead of keeping the prebuilt binaries in the repo? You know, at F-Droid the only binary components we accept are images (like PNG) :wink:

You can see [this analogue case](https://gitlab.com/fdroid/rfp/issues/756#note_110511882) on how a developer describes what is needed (I'm no dev, so my phrasing on this might be a bit off).
